name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: java pipeline
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Build
              run: |
                  chmod +x mvnw
                  ./mvnw clean package
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ -n $SONAR_TOKEN ]; then
                      ./mvnw -ntp initialize sonar:sonar -Dsonar.organization=entando-samples -Dsonar.host.url=https://sonarcloud.io
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests
